db:
  hostname: "localhost:5432"
  username: "me"
  password: "password"
  dbName: "go_testing"
api:
  port: 8000
solana:
  network: "devnet"
  privKey: [00 00 00 00 00 ...]
  accountPollRate: 30
ftx:
  apiKey: "XXXXXXXXXXXXXXXXXXXXXX"
  secret: "XXXXXXXXXXXXXXXXXXXXXX"
nomics:
  apiKey: "XXXXXXXXXXXXXXXXXx"